#ifndef _INPUT_H_
#define _INPUT_H_

#include <SDL.h>

#define JOY_DEADZONE		5000

extern int keys[2048];
extern int mouse[2];
extern int mouseMoved;
extern int enableJoystick;

enum KeyNames
{
#ifdef OGS_SDL2
	KEY_BACK	= SDL_SCANCODE_ESCAPE,
	KEY_START	= SDL_SCANCODE_RETURN,
	KEY_LEFT	= SDL_SCANCODE_LEFT,
	KEY_RIGHT	= SDL_SCANCODE_RIGHT,
	KEY_UP		= SDL_SCANCODE_UP,
	KEY_DOWN	= SDL_SCANCODE_DOWN,
	KEY_OK		= SDL_SCANCODE_LCTRL,
	KEY_CANCEL	= SDL_SCANCODE_LALT,
	KEY_EXTRA	= SDL_SCANCODE_SPACE
#else
	KEY_BACK	= SDLK_ESCAPE,
	KEY_START	= SDLK_RETURN,
	KEY_LEFT	= SDLK_LEFT,
	KEY_RIGHT	= SDLK_RIGHT,
	KEY_UP		= SDLK_UP,
	KEY_DOWN	= SDLK_DOWN,
	KEY_OK		= SDLK_LCTRL,
	KEY_CANCEL	= SDLK_LALT,
	KEY_EXTRA	= SDLK_SPACE
#endif
};

void input();
void updateMouse();

#endif /* _INPUT_H_ */
